// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greet.proto

package greetpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName           string   `protobuf:"bytes,2,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{0}
}
func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (dst *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(dst, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetSecondName() string {
	if m != nil {
		return m.SecondName
	}
	return ""
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{1}
}
func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (dst *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(dst, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{2}
}
func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (dst *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(dst, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetManyTimesRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetManyTimesRequest) Reset()         { *m = GreetManyTimesRequest{} }
func (m *GreetManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesRequest) ProtoMessage()    {}
func (*GreetManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{3}
}
func (m *GreetManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesRequest.Unmarshal(m, b)
}
func (m *GreetManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesRequest.Marshal(b, m, deterministic)
}
func (dst *GreetManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesRequest.Merge(dst, src)
}
func (m *GreetManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesRequest.Size(m)
}
func (m *GreetManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesRequest proto.InternalMessageInfo

func (m *GreetManyTimesRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetManyTimesResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyTimesResponse) Reset()         { *m = GreetManyTimesResponse{} }
func (m *GreetManyTimesResponse) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesResponse) ProtoMessage()    {}
func (*GreetManyTimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{4}
}
func (m *GreetManyTimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesResponse.Unmarshal(m, b)
}
func (m *GreetManyTimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesResponse.Marshal(b, m, deterministic)
}
func (dst *GreetManyTimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesResponse.Merge(dst, src)
}
func (m *GreetManyTimesResponse) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesResponse.Size(m)
}
func (m *GreetManyTimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesResponse proto.InternalMessageInfo

func (m *GreetManyTimesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type LongGreetrequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LongGreetrequest) Reset()         { *m = LongGreetrequest{} }
func (m *LongGreetrequest) String() string { return proto.CompactTextString(m) }
func (*LongGreetrequest) ProtoMessage()    {}
func (*LongGreetrequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{5}
}
func (m *LongGreetrequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetrequest.Unmarshal(m, b)
}
func (m *LongGreetrequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetrequest.Marshal(b, m, deterministic)
}
func (dst *LongGreetrequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetrequest.Merge(dst, src)
}
func (m *LongGreetrequest) XXX_Size() int {
	return xxx_messageInfo_LongGreetrequest.Size(m)
}
func (m *LongGreetrequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetrequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetrequest proto.InternalMessageInfo

func (m *LongGreetrequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type LongGreetresponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongGreetresponse) Reset()         { *m = LongGreetresponse{} }
func (m *LongGreetresponse) String() string { return proto.CompactTextString(m) }
func (*LongGreetresponse) ProtoMessage()    {}
func (*LongGreetresponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{6}
}
func (m *LongGreetresponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetresponse.Unmarshal(m, b)
}
func (m *LongGreetresponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetresponse.Marshal(b, m, deterministic)
}
func (dst *LongGreetresponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetresponse.Merge(dst, src)
}
func (m *LongGreetresponse) XXX_Size() int {
	return xxx_messageInfo_LongGreetresponse.Size(m)
}
func (m *LongGreetresponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetresponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetresponse proto.InternalMessageInfo

func (m *LongGreetresponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetEveryoneRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetEveryoneRequest) Reset()         { *m = GreetEveryoneRequest{} }
func (m *GreetEveryoneRequest) String() string { return proto.CompactTextString(m) }
func (*GreetEveryoneRequest) ProtoMessage()    {}
func (*GreetEveryoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{7}
}
func (m *GreetEveryoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryoneRequest.Unmarshal(m, b)
}
func (m *GreetEveryoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryoneRequest.Marshal(b, m, deterministic)
}
func (dst *GreetEveryoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryoneRequest.Merge(dst, src)
}
func (m *GreetEveryoneRequest) XXX_Size() int {
	return xxx_messageInfo_GreetEveryoneRequest.Size(m)
}
func (m *GreetEveryoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryoneRequest proto.InternalMessageInfo

func (m *GreetEveryoneRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetEveryoneresponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetEveryoneresponse) Reset()         { *m = GreetEveryoneresponse{} }
func (m *GreetEveryoneresponse) String() string { return proto.CompactTextString(m) }
func (*GreetEveryoneresponse) ProtoMessage()    {}
func (*GreetEveryoneresponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{8}
}
func (m *GreetEveryoneresponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryoneresponse.Unmarshal(m, b)
}
func (m *GreetEveryoneresponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryoneresponse.Marshal(b, m, deterministic)
}
func (dst *GreetEveryoneresponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryoneresponse.Merge(dst, src)
}
func (m *GreetEveryoneresponse) XXX_Size() int {
	return xxx_messageInfo_GreetEveryoneresponse.Size(m)
}
func (m *GreetEveryoneresponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryoneresponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryoneresponse proto.InternalMessageInfo

func (m *GreetEveryoneresponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type SquareRootRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootRequest) Reset()         { *m = SquareRootRequest{} }
func (m *SquareRootRequest) String() string { return proto.CompactTextString(m) }
func (*SquareRootRequest) ProtoMessage()    {}
func (*SquareRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{9}
}
func (m *SquareRootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootRequest.Unmarshal(m, b)
}
func (m *SquareRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootRequest.Marshal(b, m, deterministic)
}
func (dst *SquareRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootRequest.Merge(dst, src)
}
func (m *SquareRootRequest) XXX_Size() int {
	return xxx_messageInfo_SquareRootRequest.Size(m)
}
func (m *SquareRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootRequest proto.InternalMessageInfo

func (m *SquareRootRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SquareRootResponse struct {
	NumberRoot           float64  `protobuf:"fixed64,1,opt,name=number_root,json=numberRoot,proto3" json:"number_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareRootResponse) Reset()         { *m = SquareRootResponse{} }
func (m *SquareRootResponse) String() string { return proto.CompactTextString(m) }
func (*SquareRootResponse) ProtoMessage()    {}
func (*SquareRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{10}
}
func (m *SquareRootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareRootResponse.Unmarshal(m, b)
}
func (m *SquareRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareRootResponse.Marshal(b, m, deterministic)
}
func (dst *SquareRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareRootResponse.Merge(dst, src)
}
func (m *SquareRootResponse) XXX_Size() int {
	return xxx_messageInfo_SquareRootResponse.Size(m)
}
func (m *SquareRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SquareRootResponse proto.InternalMessageInfo

func (m *SquareRootResponse) GetNumberRoot() float64 {
	if m != nil {
		return m.NumberRoot
	}
	return 0
}

type GreetWithDeadRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetWithDeadRequest) Reset()         { *m = GreetWithDeadRequest{} }
func (m *GreetWithDeadRequest) String() string { return proto.CompactTextString(m) }
func (*GreetWithDeadRequest) ProtoMessage()    {}
func (*GreetWithDeadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{11}
}
func (m *GreetWithDeadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetWithDeadRequest.Unmarshal(m, b)
}
func (m *GreetWithDeadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetWithDeadRequest.Marshal(b, m, deterministic)
}
func (dst *GreetWithDeadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetWithDeadRequest.Merge(dst, src)
}
func (m *GreetWithDeadRequest) XXX_Size() int {
	return xxx_messageInfo_GreetWithDeadRequest.Size(m)
}
func (m *GreetWithDeadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetWithDeadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetWithDeadRequest proto.InternalMessageInfo

func (m *GreetWithDeadRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetWithDeadResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetWithDeadResponse) Reset()         { *m = GreetWithDeadResponse{} }
func (m *GreetWithDeadResponse) String() string { return proto.CompactTextString(m) }
func (*GreetWithDeadResponse) ProtoMessage()    {}
func (*GreetWithDeadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_a7ecb7785ae76339, []int{12}
}
func (m *GreetWithDeadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetWithDeadResponse.Unmarshal(m, b)
}
func (m *GreetWithDeadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetWithDeadResponse.Marshal(b, m, deterministic)
}
func (dst *GreetWithDeadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetWithDeadResponse.Merge(dst, src)
}
func (m *GreetWithDeadResponse) XXX_Size() int {
	return xxx_messageInfo_GreetWithDeadResponse.Size(m)
}
func (m *GreetWithDeadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetWithDeadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetWithDeadResponse proto.InternalMessageInfo

func (m *GreetWithDeadResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "greet.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greet.GreetResponse")
	proto.RegisterType((*GreetManyTimesRequest)(nil), "greet.GreetManyTimesRequest")
	proto.RegisterType((*GreetManyTimesResponse)(nil), "greet.GreetManyTimesResponse")
	proto.RegisterType((*LongGreetrequest)(nil), "greet.LongGreetrequest")
	proto.RegisterType((*LongGreetresponse)(nil), "greet.LongGreetresponse")
	proto.RegisterType((*GreetEveryoneRequest)(nil), "greet.GreetEveryoneRequest")
	proto.RegisterType((*GreetEveryoneresponse)(nil), "greet.GreetEveryoneresponse")
	proto.RegisterType((*SquareRootRequest)(nil), "greet.SquareRootRequest")
	proto.RegisterType((*SquareRootResponse)(nil), "greet.SquareRootResponse")
	proto.RegisterType((*GreetWithDeadRequest)(nil), "greet.GreetWithDeadRequest")
	proto.RegisterType((*GreetWithDeadResponse)(nil), "greet.GreetWithDeadResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetServiceClient interface {
	// unary
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	// server streaming
	GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimesClient, error)
	// stream processing
	LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error)
	// bidirectional streams
	GreetEveryone(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryoneClient, error)
	// Error handling
	SquarRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error)
	// unary
	GreetWithDeadline(ctx context.Context, in *GreetWithDeadRequest, opts ...grpc.CallOption) (*GreetWithDeadResponse, error)
}

type greetServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetServiceClient(cc *grpc.ClientConn) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/greet.GreetService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/greet.GreetService/GreetManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_GreetManyTimesClient interface {
	Recv() (*GreetManyTimesResponse, error)
	grpc.ClientStream
}

type greetServiceGreetManyTimesClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetManyTimesClient) Recv() (*GreetManyTimesResponse, error) {
	m := new(GreetManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[1], "/greet.GreetService/LongGreet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceLongGreetClient{stream}
	return x, nil
}

type GreetService_LongGreetClient interface {
	Send(*LongGreetrequest) error
	CloseAndRecv() (*LongGreetresponse, error)
	grpc.ClientStream
}

type greetServiceLongGreetClient struct {
	grpc.ClientStream
}

func (x *greetServiceLongGreetClient) Send(m *LongGreetrequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceLongGreetClient) CloseAndRecv() (*LongGreetresponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongGreetresponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) GreetEveryone(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryoneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[2], "/greet.GreetService/GreetEveryone", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetEveryoneClient{stream}
	return x, nil
}

type GreetService_GreetEveryoneClient interface {
	Send(*GreetEveryoneRequest) error
	Recv() (*GreetEveryoneresponse, error)
	grpc.ClientStream
}

type greetServiceGreetEveryoneClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetEveryoneClient) Send(m *GreetEveryoneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceGreetEveryoneClient) Recv() (*GreetEveryoneresponse, error) {
	m := new(GreetEveryoneresponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SquarRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error) {
	out := new(SquareRootResponse)
	err := c.cc.Invoke(ctx, "/greet.GreetService/SquarRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetWithDeadline(ctx context.Context, in *GreetWithDeadRequest, opts ...grpc.CallOption) (*GreetWithDeadResponse, error) {
	out := new(GreetWithDeadResponse)
	err := c.cc.Invoke(ctx, "/greet.GreetService/GreetWithDeadline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetServiceServer is the server API for GreetService service.
type GreetServiceServer interface {
	// unary
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	// server streaming
	GreetManyTimes(*GreetManyTimesRequest, GreetService_GreetManyTimesServer) error
	// stream processing
	LongGreet(GreetService_LongGreetServer) error
	// bidirectional streams
	GreetEveryone(GreetService_GreetEveryoneServer) error
	// Error handling
	SquarRoot(context.Context, *SquareRootRequest) (*SquareRootResponse, error)
	// unary
	GreetWithDeadline(context.Context, *GreetWithDeadRequest) (*GreetWithDeadResponse, error)
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).GreetManyTimes(m, &greetServiceGreetManyTimesServer{stream})
}

type GreetService_GreetManyTimesServer interface {
	Send(*GreetManyTimesResponse) error
	grpc.ServerStream
}

type greetServiceGreetManyTimesServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetManyTimesServer) Send(m *GreetManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_LongGreet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).LongGreet(&greetServiceLongGreetServer{stream})
}

type GreetService_LongGreetServer interface {
	SendAndClose(*LongGreetresponse) error
	Recv() (*LongGreetrequest, error)
	grpc.ServerStream
}

type greetServiceLongGreetServer struct {
	grpc.ServerStream
}

func (x *greetServiceLongGreetServer) SendAndClose(m *LongGreetresponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceLongGreetServer) Recv() (*LongGreetrequest, error) {
	m := new(LongGreetrequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_GreetEveryone_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).GreetEveryone(&greetServiceGreetEveryoneServer{stream})
}

type GreetService_GreetEveryoneServer interface {
	Send(*GreetEveryoneresponse) error
	Recv() (*GreetEveryoneRequest, error)
	grpc.ServerStream
}

type greetServiceGreetEveryoneServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetEveryoneServer) Send(m *GreetEveryoneresponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceGreetEveryoneServer) Recv() (*GreetEveryoneRequest, error) {
	m := new(GreetEveryoneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_SquarRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).SquarRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetService/SquarRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).SquarRoot(ctx, req.(*SquareRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetWithDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetWithDeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).GreetWithDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetService/GreetWithDeadline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).GreetWithDeadline(ctx, req.(*GreetWithDeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreetService_Greet_Handler,
		},
		{
			MethodName: "SquarRoot",
			Handler:    _GreetService_SquarRoot_Handler,
		},
		{
			MethodName: "GreetWithDeadline",
			Handler:    _GreetService_GreetWithDeadline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetManyTimes",
			Handler:       _GreetService_GreetManyTimes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LongGreet",
			Handler:       _GreetService_LongGreet_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GreetEveryone",
			Handler:       _GreetService_GreetEveryone_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "greet.proto",
}

func init() { proto.RegisterFile("greet.proto", fileDescriptor_greet_a7ecb7785ae76339) }

var fileDescriptor_greet_a7ecb7785ae76339 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x8b, 0xda, 0x40,
	0x14, 0x35, 0x15, 0xad, 0xb9, 0xe9, 0x97, 0x53, 0x6b, 0x6d, 0xaa, 0x58, 0xf2, 0x52, 0x41, 0xb0,
	0x62, 0xdb, 0xa7, 0x3e, 0x14, 0xac, 0xa5, 0x50, 0xda, 0x62, 0x63, 0xa1, 0xb0, 0x2f, 0x12, 0xf5,
	0x6e, 0x36, 0x60, 0x66, 0x74, 0x92, 0x08, 0xfe, 0xbe, 0xfd, 0x63, 0x4b, 0x66, 0x26, 0xd9, 0x24,
	0xba, 0x2b, 0xb8, 0x6f, 0xde, 0x7b, 0x4e, 0xce, 0xb9, 0x37, 0xf7, 0x18, 0x30, 0x5c, 0x8e, 0x18,
	0x0e, 0x36, 0x9c, 0x85, 0x8c, 0x54, 0x44, 0x61, 0xfd, 0x84, 0xda, 0x8f, 0xf8, 0x87, 0x47, 0x5d,
	0xd2, 0x01, 0xb8, 0xf4, 0x78, 0x10, 0xce, 0xa9, 0xe3, 0x63, 0x4b, 0x7b, 0xa7, 0xf5, 0x74, 0x5b,
	0x17, 0x9d, 0x3f, 0x8e, 0x8f, 0xa4, 0x0b, 0x46, 0x80, 0x4b, 0x46, 0x57, 0x12, 0x7f, 0x24, 0x70,
	0x90, 0xad, 0x98, 0x60, 0x7d, 0x81, 0x27, 0x42, 0xcb, 0xc6, 0x6d, 0x84, 0x41, 0x48, 0xfa, 0x50,
	0x73, 0x95, 0xb6, 0x50, 0x33, 0x46, 0xcf, 0x07, 0x72, 0x84, 0xc4, 0xd2, 0x4e, 0x09, 0xd6, 0x7b,
	0x78, 0xaa, 0x1e, 0x0e, 0x36, 0x8c, 0x06, 0x48, 0x9a, 0x50, 0xe5, 0x18, 0x44, 0xeb, 0x50, 0x4d,
	0xa2, 0x2a, 0x6b, 0x02, 0xaf, 0x04, 0xf1, 0xb7, 0x43, 0xf7, 0xff, 0x3c, 0x1f, 0x83, 0xb3, 0xec,
	0x86, 0xd0, 0x2c, 0xaa, 0x9c, 0xf0, 0xfd, 0x0a, 0x2f, 0x7e, 0x31, 0xea, 0x8a, 0xa7, 0xf8, 0x39,
	0x96, 0x7d, 0xa8, 0x67, 0x04, 0x4e, 0xb8, 0x7d, 0x83, 0x86, 0x20, 0x7e, 0xdf, 0x21, 0xdf, 0x33,
	0x8a, 0x67, 0x2d, 0xf9, 0x41, 0xbd, 0xaa, 0x44, 0xe4, 0xa4, 0x6b, 0x1f, 0xea, 0xb3, 0x6d, 0xe4,
	0x70, 0xb4, 0x19, 0x4b, 0xcf, 0xd8, 0x84, 0x2a, 0x8d, 0xfc, 0x05, 0x72, 0x41, 0x2e, 0xdb, 0xaa,
	0xb2, 0x3e, 0x03, 0xc9, 0x92, 0x95, 0x74, 0x17, 0x0c, 0x89, 0xcf, 0x39, 0x63, 0x52, 0x5f, 0xb3,
	0x41, 0xb6, 0x62, 0x62, 0xba, 0xd9, 0x7f, 0x2f, 0xbc, 0x9a, 0xa0, 0xb3, 0x7a, 0xd0, 0x66, 0xb7,
	0x22, 0xf7, 0x6f, 0x36, 0xba, 0x2e, 0xab, 0x70, 0xce, 0x90, 0xef, 0xbc, 0x25, 0x92, 0x4f, 0x50,
	0x11, 0x35, 0x79, 0x99, 0x75, 0x51, 0xc3, 0x98, 0x8d, 0x7c, 0x53, 0x8a, 0x5b, 0x25, 0xf2, 0x17,
	0x9e, 0xe5, 0x63, 0x43, 0xda, 0x59, 0x66, 0x31, 0x93, 0x66, 0xe7, 0x0e, 0x34, 0x11, 0x1c, 0x6a,
	0x64, 0x0c, 0x7a, 0x1a, 0x0b, 0xf2, 0x5a, 0xf1, 0x8b, 0x49, 0x33, 0x5b, 0x87, 0x40, 0xa2, 0xd1,
	0xd3, 0xc8, 0x54, 0xfd, 0x79, 0x92, 0x43, 0x93, 0xb7, 0x59, 0xdf, 0x42, 0x86, 0xcc, 0xf6, 0x31,
	0x30, 0xab, 0x27, 0xa7, 0x12, 0xc7, 0x8d, 0x4f, 0x46, 0x12, 0xf3, 0x83, 0x6c, 0x98, 0x6f, 0x8e,
	0x20, 0xe9, 0xcb, 0x9a, 0x42, 0x3d, 0x77, 0xa4, 0xb5, 0x57, 0x9c, 0xac, 0x90, 0x81, 0xfc, 0x64,
	0xc5, 0xdb, 0x5a, 0xa5, 0xb1, 0x7e, 0xf1, 0x58, 0x10, 0x36, 0x8b, 0x45, 0x55, 0x7c, 0xc6, 0x3e,
	0xde, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xf7, 0x98, 0x94, 0xd5, 0x04, 0x00, 0x00,
}
